version: 2
updates:
  # Enable version updates for NuGet packages
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "my-org/dependabot-reviewers"
    assignees:
      - "REPO_OWNER_OR_TEAM"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    groups:
      microsoft-extensions:
        patterns:
          - "Microsoft.Extensions.*"
      entity-framework:
        patterns:
          - "Microsoft.EntityFrameworkCore*"
      serilog:
        patterns:
          - "Serilog*"
      testing:
        patterns:
          - "xunit*"
          - "Microsoft.NET.Test.Sdk"
          - "coverlet*"
    ignore:
      # Ignore major version updates for stable packages
      - dependency-name: "Microsoft.EntityFrameworkCore*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "Microsoft.Extensions.*"
        update-types: ["version-update:semver-major"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
      include: "scope"
